---
- name: Install Node.js development tools
  hosts: all
  gather_facts: true
  roles:
    - role: software
      software_name: language/node
      software_packages:
        Debian: [nodejs, npm]
        Archlinux: [nodejs, npm]
        RedHat: [nodejs, npm]
        Suse: [nodejs, npm]
      software_verify: [[node, --version], [npm, --version]]
