---
- name: Install Helix
  hosts: all
  gather_facts: true
  roles:
    - role: software
      software_name: ide/helix
      software_packages:
        Debian: [helix]
        Archlinux: [helix]
        RedHat: [helix]
        Suse: [helix]
      software_verify: [[hx, --version]]
