---
- name: Install Neovim
  hosts: all
  gather_facts: true
  roles:
    - role: software
      software_name: ide/neovim
      software_packages:
        Debian: [neovim]
        Archlinux: [neovim]
        RedHat: [neovim]
        Suse: [neovim]
      software_verify: [[nvim, --version]]
