---
- name: Install the xfce desktop with VNC
  hosts: all
  gather_facts: true
  roles:
    - role: desktop-vnc
      desktop_session: xfce
      desktop_packages: ["xfce4","xfce4-terminal"]
      desktop_arch_packages: ["xfce4-session", "xfce4-panel", "xfce4-settings", "xfdesktop", "xfwm4", "thunar", "xfce4-terminal"]
      desktop_argv: ["startxfce4"]
