---
- name: Install GNOME Web
  hosts: all
  gather_facts: true
  roles:
    - role: software
      software_name: browser/epiphany
      software_packages:
        Debian: [epiphany-browser]
        Archlinux: [epiphany]
        RedHat: [epiphany]
        Suse: [epiphany]
      software_verify: [[epiphany, --version]]
