---
- name: Install Firefox
  hosts: all
  gather_facts: true
  roles:
    - role: software
      software_name: browser/firefox
      software_packages:
        Debian: [firefox-esr]
        Archlinux: [firefox]
        RedHat: [firefox]
        Suse: [MozillaFirefox]
      software_verify: [[firefox, --version]]
